CREATE USER IF NOT EXISTS "SA" SALT '680d4e1b204a8de0' HASH 'b37eb5c48ac7823e03b325a87ba73b84132361b15ef83fcfd37a13f9a59ce350' ADMIN;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "PUBLIC"."CITY"(
    "CITY_CODE" BIGINT NOT NULL,
    "CITY_DESCRIPTION" VARCHAR(200) NOT NULL,
    "CITY_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."CITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("CITY_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CITY;
CREATE MEMORY TABLE "PUBLIC"."CLIENT"(
    "CLIENT_CODE" BIGINT NOT NULL,
    "CLIENT_ADDRESS" VARCHAR(70) NOT NULL,
    "CLIENT_IDENTIFICATION_NUMBER" VARCHAR(20) NOT NULL,
    "CLIENT_IDENTIFICATION_TYPE" VARCHAR(5) NOT NULL,
    "CLIENT_NAME" VARCHAR(50) NOT NULL,
    "CLIENT_PHONE_NUMBER" VARCHAR(20) NOT NULL,
    "CLIENT_PICTURE" VARCHAR(255) NOT NULL,
    "CLIENT_CITY_CODE" BIGINT NOT NULL,
    "CLIENT_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("CLIENT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENT;
CREATE MEMORY TABLE "PUBLIC"."DEPARTAMENT"(
    "DEPARTAMENT_CODE" BIGINT NOT NULL,
    "DEPARTAMENT_DESCRIPTION" VARCHAR(200) NOT NULL
);
ALTER TABLE "PUBLIC"."DEPARTAMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("DEPARTAMENT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTAMENT;
CREATE MEMORY TABLE "PUBLIC"."INVOICEDETAIL"(
    "INVOICE_ITEM_CONSECUTIVE" BIGINT NOT NULL,
    "PRODUCT_CANT" INTEGER NOT NULL,
    "INVOICE_NUMBER" BIGINT NOT NULL,
    "PRODUCT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("INVOICE_ITEM_CONSECUTIVE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INVOICEDETAIL;
CREATE MEMORY TABLE "PUBLIC"."INVOICEHEADER"(
    "INVOICE_NUMBER" BIGINT NOT NULL,
    "INVOICE_ADDRESS" VARCHAR(50) NOT NULL,
    "INVOICE_DATE" TIMESTAMP NOT NULL,
    "INVOICE_PHONE" VARCHAR(20) NOT NULL,
    "INVOICE_TYPE" VARCHAR(15) NOT NULL,
    "INVOICE_TOTAL" DOUBLE NOT NULL,
    "INVOICE_CITY_CODE" BIGINT NOT NULL,
    "INVOICE_CLIENT_CODE" BIGINT NOT NULL,
    "INVOICE_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" PRIMARY KEY("INVOICE_NUMBER");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INVOICEHEADER;
CREATE MEMORY TABLE "PUBLIC"."MATERIAL"(
    "MATERIAL_CODE" BIGINT NOT NULL,
    "MATERIAL_DESCRIPTION" VARCHAR(150) NOT NULL,
    "MATERIAL_PRICE" DOUBLE NOT NULL
);
ALTER TABLE "PUBLIC"."MATERIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("MATERIAL_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MATERIAL;
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "PRODUCT_CODE" BIGINT NOT NULL,
    "PRODUCT_CREATE_DATE" TIMESTAMP NOT NULL,
    "PRODUCT_DESCRIPTION" VARCHAR(200) NOT NULL,
    "PRODUCT_TAX" DOUBLE NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("PRODUCT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE MEMORY TABLE "PUBLIC"."PRODUCTDETAIL"(
    "PRODUCT_DETAIL_CODE" BIGINT NOT NULL,
    "MATERIAL_CANT" INTEGER NOT NULL,
    "MATERIAL_PRICE" DOUBLE NOT NULL,
    "MATERIAL_CODE" BIGINT NOT NULL,
    "PRODUCT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_14" PRIMARY KEY("PRODUCT_DETAIL_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTDETAIL;
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."FKAVL3Y2PCKJ4N00K6XOTBJP77F" FOREIGN KEY("PRODUCT_CODE") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FK10YFJ4J735JILLB1SYFRMJIC7" FOREIGN KEY("INVOICE_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."FKDJ73L2G2ILPGAQ40YD22E0NNM" FOREIGN KEY("MATERIAL_CODE") REFERENCES "PUBLIC"."MATERIAL"("MATERIAL_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."FKK2M1D75I03SFQ9FA6HSW2UN91" FOREIGN KEY("PRODUCT_CODE") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."FKLIY6WD56FWAVLQ8G3YJJBVY22" FOREIGN KEY("CLIENT_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."FK5Q6ME68QQCWI7KEHU1DDF8RT6" FOREIGN KEY("CLIENT_CITY_CODE") REFERENCES "PUBLIC"."CITY"("CITY_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FKN50740I6G06S1ME4F1PKE4E30" FOREIGN KEY("INVOICE_CITY_CODE") REFERENCES "PUBLIC"."CITY"("CITY_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."FKLFCJXXPS9GR0DCUUGW1A8AQC6" FOREIGN KEY("INVOICE_NUMBER") REFERENCES "PUBLIC"."INVOICEHEADER"("INVOICE_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."CITY" ADD CONSTRAINT "PUBLIC"."FK53XTQS96QBUW8NXV74QIGXJ48" FOREIGN KEY("CITY_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FKQ18GMY4OHKYCOW30BK2JN3GG3" FOREIGN KEY("INVOICE_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE") NOCHECK;