CREATE USER IF NOT EXISTS "SA" SALT 'e7e04b73992c8b5b' HASH 'dd1d2cc4ff62813cde67ef506284c59600fe7740a60ea16c15838199057221e0' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9013DA71_9C7A_4B8A_A1BB_5661FEBD8DA6" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_84C0D3DD_82DB_469D_911E_22F369646897" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F75916E_AF45_4A0E_8BBC_F6B1D25019DA" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9C8849E8_B3A8_4F58_99C7_C3900E5CBA85" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EC551E40_3215_4B45_BCF5_E65E0F00B680" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A9D8E0D9_7776_422D_8CCB_34461B69FC7E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D9619646_78FE_4F30_9A15_BC8144684640" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C96D9E92_DE1E_4DE6_B60B_8407B444C796" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."CITY"(
    "CITY_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A9D8E0D9_7776_422D_8CCB_34461B69FC7E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A9D8E0D9_7776_422D_8CCB_34461B69FC7E",
    "CITY_DESCRIPTION" VARCHAR(200) NOT NULL,
    "CITY_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."CITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("CITY_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CITY;
CREATE MEMORY TABLE "PUBLIC"."CLIENT"(
    "CLIENT_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9013DA71_9C7A_4B8A_A1BB_5661FEBD8DA6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9013DA71_9C7A_4B8A_A1BB_5661FEBD8DA6",
    "CLIENT_ADDRESS" VARCHAR(70) NOT NULL,
    "CLIENT_IDENTIFICATION_NUMBER" VARCHAR(20) NOT NULL,
    "CLIENT_IDENTIFICATION_TYPE" VARCHAR(5) NOT NULL,
    "CLIENT_NAME" VARCHAR(50) NOT NULL,
    "CLIENT_PHONE_NUMBER" VARCHAR(20) NOT NULL,
    "CLIENT_PICTURE" VARCHAR(255) NOT NULL,
    "CLIENT_CITY_CODE" BIGINT NOT NULL,
    "CLIENT_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("CLIENT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENT;
CREATE MEMORY TABLE "PUBLIC"."DEPARTAMENT"(
    "DEPARTAMENT_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5F75916E_AF45_4A0E_8BBC_F6B1D25019DA" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F75916E_AF45_4A0E_8BBC_F6B1D25019DA",
    "DEPARTAMENT_DESCRIPTION" VARCHAR(200) NOT NULL
);
ALTER TABLE "PUBLIC"."DEPARTAMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("DEPARTAMENT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTAMENT;
CREATE MEMORY TABLE "PUBLIC"."INVOICEDETAIL"(
    "INVOICE_ITEM_CONSECUTIVE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D9619646_78FE_4F30_9A15_BC8144684640" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D9619646_78FE_4F30_9A15_BC8144684640",
    "PRODUCT_CANT" INTEGER NOT NULL,
    "INVOICE_NUMBER" BIGINT NOT NULL,
    "PRODUCT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("INVOICE_ITEM_CONSECUTIVE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INVOICEDETAIL;
CREATE MEMORY TABLE "PUBLIC"."INVOICEHEADER"(
    "INVOICE_NUMBER" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9C8849E8_B3A8_4F58_99C7_C3900E5CBA85" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9C8849E8_B3A8_4F58_99C7_C3900E5CBA85",
    "INVOICE_ADDRESS" VARCHAR(50) NOT NULL,
    "INVOICE_DATE" TIMESTAMP NOT NULL,
    "INVOICE_PHONE" VARCHAR(20) NOT NULL,
    "INVOICE_TYPE" VARCHAR(15) NOT NULL,
    "INVOICE_TOTAL" DOUBLE NOT NULL,
    "INVOICE_CITY_CODE" BIGINT NOT NULL,
    "INVOICE_CLIENT_CODE" BIGINT NOT NULL,
    "INVOICE_DEPARTAMENT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" PRIMARY KEY("INVOICE_NUMBER");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INVOICEHEADER;
CREATE MEMORY TABLE "PUBLIC"."MATERIAL"(
    "MATERIAL_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C96D9E92_DE1E_4DE6_B60B_8407B444C796" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C96D9E92_DE1E_4DE6_B60B_8407B444C796",
    "MATERIAL_DESCRIPTION" VARCHAR(150) NOT NULL,
    "MATERIAL_PRICE" DOUBLE NOT NULL
);
ALTER TABLE "PUBLIC"."MATERIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("MATERIAL_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MATERIAL;
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "PRODUCT_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_EC551E40_3215_4B45_BCF5_E65E0F00B680" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EC551E40_3215_4B45_BCF5_E65E0F00B680",
    "PRODUCT_CREATE_DATE" TIMESTAMP NOT NULL,
    "PRODUCT_DESCRIPTION" VARCHAR(200) NOT NULL,
    "PRODUCT_TAX" DOUBLE NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("PRODUCT_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE MEMORY TABLE "PUBLIC"."PRODUCTDETAIL"(
    "PRODUCT_DETAIL_CODE" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_84C0D3DD_82DB_469D_911E_22F369646897" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_84C0D3DD_82DB_469D_911E_22F369646897",
    "MATERIAL_CANT" INTEGER NOT NULL,
    "MATERIAL_PRICE" DOUBLE NOT NULL,
    "MATERIAL_CODE" BIGINT NOT NULL,
    "PRODUCT_CODE" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_14" PRIMARY KEY("PRODUCT_DETAIL_CODE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTDETAIL;
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."FKAVL3Y2PCKJ4N00K6XOTBJP77F" FOREIGN KEY("PRODUCT_CODE") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FK10YFJ4J735JILLB1SYFRMJIC7" FOREIGN KEY("INVOICE_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCTDETAIL" ADD CONSTRAINT "PUBLIC"."FKDJ73L2G2ILPGAQ40YD22E0NNM" FOREIGN KEY("MATERIAL_CODE") REFERENCES "PUBLIC"."MATERIAL"("MATERIAL_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."FKK2M1D75I03SFQ9FA6HSW2UN91" FOREIGN KEY("PRODUCT_CODE") REFERENCES "PUBLIC"."PRODUCT"("PRODUCT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."FKLIY6WD56FWAVLQ8G3YJJBVY22" FOREIGN KEY("CLIENT_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."FK5Q6ME68QQCWI7KEHU1DDF8RT6" FOREIGN KEY("CLIENT_CITY_CODE") REFERENCES "PUBLIC"."CITY"("CITY_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FKN50740I6G06S1ME4F1PKE4E30" FOREIGN KEY("INVOICE_CITY_CODE") REFERENCES "PUBLIC"."CITY"("CITY_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEDETAIL" ADD CONSTRAINT "PUBLIC"."FKLFCJXXPS9GR0DCUUGW1A8AQC6" FOREIGN KEY("INVOICE_NUMBER") REFERENCES "PUBLIC"."INVOICEHEADER"("INVOICE_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."CITY" ADD CONSTRAINT "PUBLIC"."FK53XTQS96QBUW8NXV74QIGXJ48" FOREIGN KEY("CITY_DEPARTAMENT_CODE") REFERENCES "PUBLIC"."DEPARTAMENT"("DEPARTAMENT_CODE") NOCHECK;
ALTER TABLE "PUBLIC"."INVOICEHEADER" ADD CONSTRAINT "PUBLIC"."FKQ18GMY4OHKYCOW30BK2JN3GG3" FOREIGN KEY("INVOICE_CLIENT_CODE") REFERENCES "PUBLIC"."CLIENT"("CLIENT_CODE") NOCHECK;